apiVersion: apps/v1
kind: Deployment
metadata:
  name: Exchange
  labels:
    app: Exchange
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Exchange
  template:
    metadata:
      labels:
        app: Exchange
    spec:
      containers:
        - name: Exchange
          image: username/Exchange:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5